---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: calico-cni
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cni: calico
  resources:
  - name: calico-crs-configmap
    kind: ConfigMap
  strategy: ApplyOnce