#cloud-config
# Cloud-init configuration for CAPI worker nodes

package_update: true
package_upgrade: true

packages:
  - docker.io
  - kubectl
  - curl
  - jq

runcmd:
  # Configure Docker
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker azureuser

  # Install kubectl
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - rm kubectl

  # Format and mount data disk for container storage
  - mkfs.ext4 /dev/disk/azure/scsi1/lun0
  - mkdir -p /var/lib/docker-data
  - mount /dev/disk/azure/scsi1/lun0 /var/lib/docker-data
  - echo "/dev/disk/azure/scsi1/lun0 /var/lib/docker-data ext4 defaults,nofail 0 2" >> /etc/fstab

  # Configure Docker to use data disk
  - systemctl stop docker
  - mkdir -p /etc/docker
  - echo '{"data-root": "/var/lib/docker-data"}' > /etc/docker/daemon.json
  - systemctl start docker

write_files:
  - path: /etc/sysctl.d/99-kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

  - path: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter

final_message: "CAPI Worker node initialization complete. System is ready after $UPTIME seconds"