apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: k0s-demo-cluster
  namespace: default
  labels:
    environment: demo
    cni: calico
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.245.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: k0s-demo-cluster-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: k0s-demo-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: k0s-demo-cluster
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: k0s-demo-cluster-cp
  namespace: default
spec:
  version: v1.28.3+k0s.0
  persistence:
    type: emptyDir
  service:
    type: NodePort
  replicas: 3
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: k0s-demo-cluster-md-0
  namespace: default
spec:
  clusterName: k0s-demo-cluster
  replicas: 2
  selector:
    matchLabels: {}
  template:
    spec:
      clusterName: k0s-demo-cluster
      version: v1.28.3
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: k0s-demo-cluster-md-0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: k0s-demo-cluster-md-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: k0s-demo-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      extraMounts:
        - containerPath: /var/run/docker.sock
          hostPath: /var/run/docker.sock
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: k0s-demo-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      version: v1.28.3+k0s.0
      args:
        - --labels=node.k0sproject.io/role=worker